// <auto-generated />
namespace WebSiteTemplete.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitalConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "202207031329236_InitalConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
