//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteTemplete.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSiteTemplete.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement Style.
        /// </summary>
        public static string AddMeasurementStyle {
            get {
                return ResourceManager.GetString("AddMeasurementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artfa.
        /// </summary>
        public static string artfa {
            get {
                return ResourceManager.GetString("artfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Tailor.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No..
        /// </summary>
        public static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagories Arabic.
        /// </summary>
        public static string CatagoriesAr {
            get {
                return ResourceManager.GetString("CatagoriesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagories English.
        /// </summary>
        public static string CatagoriesEn {
            get {
                return ResourceManager.GetString("CatagoriesEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagory.
        /// </summary>
        public static string Catagory {
            get {
                return ResourceManager.GetString("Catagory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagory Name.
        /// </summary>
        public static string CatagoryId {
            get {
                return ResourceManager.GetString("CatagoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of thups Factory Tailor.
        /// </summary>
        public static string ChartFactoryTailor {
            get {
                return ResourceManager.GetString("ChartFactoryTailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of thups Shop Tailor.
        /// </summary>
        public static string ChartShopTailor {
            get {
                return ResourceManager.GetString("ChartShopTailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Arabic.
        /// </summary>
        public static string ColorAr {
            get {
                return ResourceManager.GetString("ColorAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color English.
        /// </summary>
        public static string ColorEn {
            get {
                return ResourceManager.GetString("ColorEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color Name.
        /// </summary>
        public static string ColorId {
            get {
                return ResourceManager.GetString("ColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Order.
        /// </summary>
        public static string ConfirmOrder {
            get {
                return ResourceManager.GetString("ConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Arabic Name.
        /// </summary>
        public static string CustomerArName {
            get {
                return ResourceManager.GetString("CustomerArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer English Name.
        /// </summary>
        public static string CustomerEnName {
            get {
                return ResourceManager.GetString("CustomerEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Phone.
        /// </summary>
        public static string CustomerPhone {
            get {
                return ResourceManager.GetString("CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Delete?.
        /// </summary>
        public static string DELETEQ {
            get {
                return ResourceManager.GetString("DELETEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Catagory.
        /// </summary>
        public static string EditCatagory {
            get {
                return ResourceManager.GetString("EditCatagory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Color.
        /// </summary>
        public static string EditColor {
            get {
                return ResourceManager.GetString("EditColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Measurement Style.
        /// </summary>
        public static string EditMeasurementStyle {
            get {
                return ResourceManager.GetString("EditMeasurementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string EditPermission {
            get {
                return ResourceManager.GetString("EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Statue.
        /// </summary>
        public static string EditStatue {
            get {
                return ResourceManager.GetString("EditStatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabk.
        /// </summary>
        public static string Kabk {
            get {
                return ResourceManager.GetString("Kabk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder.
        /// </summary>
        public static string Katf {
            get {
                return ResourceManager.GetString("Katf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khabnah Style.
        /// </summary>
        public static string KhabnahStyle {
            get {
                return ResourceManager.GetString("KhabnahStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kom.
        /// </summary>
        public static string Kom {
            get {
                return ResourceManager.GetString("Kom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Kom Style.
        /// </summary>
        public static string KomStyle {
            get {
                return ResourceManager.GetString("KomStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafsal.
        /// </summary>
        public static string Mafsal {
            get {
                return ResourceManager.GetString("Mafsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Order per Day.
        /// </summary>
        public static string MaxOrder {
            get {
                return ResourceManager.GetString("MaxOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Style.
        /// </summary>
        public static string MeasurementStyle {
            get {
                return ResourceManager.GetString("MeasurementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        public static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Neck Style.
        /// </summary>
        public static string NeckStyle {
            get {
                return ResourceManager.GetString("NeckStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string newAccount {
            get {
                return ResourceManager.GetString("newAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Number.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Page.
        /// </summary>
        public static string OrderPage {
            get {
                return ResourceManager.GetString("OrderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Permission Types.
        /// </summary>
        public static string PermissionTypes {
            get {
                return ResourceManager.GetString("PermissionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print This Page.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Arabic.
        /// </summary>
        public static string ProductAr {
            get {
                return ResourceManager.GetString("ProductAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product English.
        /// </summary>
        public static string ProductEn {
            get {
                return ResourceManager.GetString("ProductEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ProductQTY {
            get {
                return ResourceManager.GetString("ProductQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve Date.
        /// </summary>
        public static string RecieveDate {
            get {
                return ResourceManager.GetString("RecieveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remain {
            get {
                return ResourceManager.GetString("Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remmber Me?.
        /// </summary>
        public static string RemmberMe {
            get {
                return ResourceManager.GetString("RemmberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Tailor Report.
        /// </summary>
        public static string ReportFactoryTailor {
            get {
                return ResourceManager.GetString("ReportFactoryTailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Tailor Report.
        /// </summary>
        public static string ReportShopTailor {
            get {
                return ResourceManager.GetString("ReportShopTailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-left.
        /// </summary>
        public static string rowdirection {
            get {
                return ResourceManager.GetString("rowdirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Here....
        /// </summary>
        public static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select --.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Tailor.
        /// </summary>
        public static string ShopTailor {
            get {
                return ResourceManager.GetString("ShopTailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DashBoard.
        /// </summary>
        public static string ShowDashBoard {
            get {
                return ResourceManager.GetString("ShowDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Numbers.
        /// </summary>
        public static string ShowInNumbers {
            get {
                return ResourceManager.GetString("ShowInNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statue Arabic Name.
        /// </summary>
        public static string StatueArName {
            get {
                return ResourceManager.GetString("StatueArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statue English Name.
        /// </summary>
        public static string StatueEnName {
            get {
                return ResourceManager.GetString("StatueEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statues.
        /// </summary>
        public static string Statues {
            get {
                return ResourceManager.GetString("Statues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmed Successfully!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailor Facrory.
        /// </summary>
        public static string TailorFacrory {
            get {
                return ResourceManager.GetString("TailorFacrory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string TEXT_ALIGN {
            get {
                return ResourceManager.GetString("TEXT-ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Another Day!.
        /// </summary>
        public static string TryAnotherDay {
            get {
                return ResourceManager.GetString("TryAnotherDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        public static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Waist Style.
        /// </summary>
        public static string WaistStyle {
            get {
                return ResourceManager.GetString("WaistStyle", resourceCulture);
            }
        }
    }
}
